version: '3'

services:
  todoapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: todo-docker
    container_name: todo
    restart: always 
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      SECRET_JWT: ${SECRET_JWT}

  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: Agilesoft
    volumes:
      - ./postgres:/var/lib/postgresql/data