version: '3'

services: 
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: Agilesoft
    volumes:
      - ./postgres:/var/lib/postgresql/data
